---
title: Ethan Turkeltaub
timezone: America/New_York
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    permalink: "/notes/:title/"
    layout: note
- scope:
    path: ''
    type: pages
  values:
    layout: page
url: http://ethnt.me
permalink: pretty
primary_color: "#c7d4be"
ga: UA-33270842-1
typekit: tbr5vxj
social:
- name: Twitter
  url: https://twitter.com/ethnt
- name: GitHub
  url: https://github.com/ethnt
sass:
  style: compressed
exclude:
- node_modules/
- Gemfile*
- Gulpfile.js
- package.json
- README.md
- yarn.lock
