---
title: Ethan Turkeltaub
timezone: America/New_York
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    permalink: "/notes/:title/"
    layout: note
url: http://ethnt.me
permalink: pretty
ga: UA-33270842-1
social:
- name: Twitter
  url: https://twitter.com/ethnt
- name: GitHub
  url: https://github.com/ethnt
- name: Tumblr
  url: http://ethnt.tumblr.com
sass:
  style: compressed
exclude:
- 'node_modules/'
- 'Gemfile*'
- 'Gulpfile.js'
- 'package.json'
- 'README.md'
- 'yarn.lock'
