---
title: Ethan Turkeltaub
timezone: America/New_York
collections:
  uploads:
    title: Uploads
    output: true
  experience:
    title: Experience
    output: false
    position: 1
    on_page: true
  education:
    title: Education
    output: false
    position: 2
    on_page: true
  projects:
    title: Projects
    output: false
    position: 3
    on_page: true
  awards:
    title: Awards
    output: false
    position: 4
    on_page: true
defaults:
- scope:
    path: ''
    type: pages
  values:
    layout: page
url: http://ethnt.me
permalink: pretty
primary_color: "#c7d4be"
avatar_url: "/uploads/avatar.jpg"
google_analytics: UA-33270842-1
typekit: tbr5vxj
social:
- name: Twitter
  url: https://twitter.com/ethnt
- name: GitHub
  url: https://github.com/ethnt
sass:
  style: compressed
exclude:
- node_modules/
- Gemfile*
- Gulpfile.js
- package.json
- README.md
- yarn.lock
